### ISSUE TITLE
Add Italian Language

### ISSUE THREAD

**Issue by tekres** [Clam-/TraditionalT9#10]
I am not sure if i should write this here, is not really an issue, just a request to add italian language. I own an LG wine smart, and this is the only keyboard to integrate with the hardware keypad and works 10 times better than LG standard T9. As suggestion you should add a device compatibility list on the google app page adding LG wine smart in it for faster search. ( i went crazy to try tons and finally found yours) Keep up the good work.

**Comment by Clam-** [comment]
Hi,

Here is fine. For Italian support I would need a [few things](https://github.com/Clam-/TraditionalT9/wiki/New-Language-support):
From that link some of it is a bit technical but don't worry too much about it. Basically I need a dictionary/word list/spelling list of Italian words to add, what special characters should appear when you press each number (you can probably borrow from existing [enMap](https://github.com/Clam-/TraditionalT9/blob/master/src/org/nyanya/android/traditionalt9/CharMap.java#L18), and translation of the resources in the linked wiki page.

If you need any assistance with gathering those things feel free to let me know (I probably won't be able to help finding a dictionary/word list for you though, nor translating as I don't know any Italian.)
You can either reply here or collaborate via e-mail, either is fine.

Since I've only designed the UI around my own device (007SH) it would be unfair for me to list every device the phone actually works on, since I believe a number of devices it looks not very nice on. (That's something I'm going to address in the future, and when I do, I'll probably list some of the more popular devices on the app page.)

Thank you for your feedback, suggestions, and request.

**Comment by Clam-** [comment]
This was added in 1b15cd0
