### ISSUE TITLE
Not able to download from Play Store

### ISSUE THREAD

**Issue by frenchcharly** [Clam-/TraditionalT9#14]
It says my phone isn't compatible (Musashi Freetel). Any indications on how to get it ? ^^

**Comment by Clam-** [comment]
The problem is that Google Play Store thinks your phone doesn't have a 12 key keypad or a QWERTY keypad.
Recently this has become a problem where manufacturers give Google incorrect information about the phone's hardware. I set the package to require devices to have a hardware keyboard of either 12 key, or QWERTY keypad because the package doesn't work with touch alone.
The reason for this requirement is that there were a very high number of users installing the package when they didn't have a hardware keypad then requesting assistance or saying it didn't work. It was consuming quite a bit of time.

I have tried contacting Google Play Store in the past to get them to correct information about a device in their database but they said only the manufacturer can do this. They suggested people contact the manufacturer to get them to give updated details to Google.

You can install the package manually if you wish:
http://nyanya.org/android/TraditionalT9-git-e08c4a4.apk

I don't think there is anything I can do about manufacturers supplying incorrect information to Google Play. Users likely need to petition the manufacturers to update information with Google.

**Comment by iaros** [comment]
I am not familiar with Play Store but can't you additionally add specific models to be allowed to download the package?

**Comment by Clam-** [comment]
While it's true you can manually allow/block devices on the app store, once you have set a manifest restriction, you cannot override it.
https://nyanya.org/android/imgs/unsupported.png

Unless something changes on Google Plays backend I cannot override "unsupported" devices to allow.
Please notice the "unsupported devices":
https://nyanya.org/android/imgs/unsupported2.png

Many of those are either bots, or confused users that will install the app thinking it's something it is not. It's difficult to have to deal with the many queries relating to devices I don't intend to support.

Very sorry for the inconvenience.

**Comment by iaros** [comment]
Thank you for the clarification.
