### ISSUE TITLE
Feature request: Back button in a keyboard to delete text

### ISSUE THREAD

**Issue by Bamasam** [Clam-/TraditionalT9#24]
Hi. I am using a Uniwa T301 phone. 

I am using the Traditional T9, version git-e08c4a4

Here is the keyboard and its layout.
The problem is, atleast with the current version of The Traditional T9 I use. There is no way to delete text.
The phone does not have a separate "Delete" key. 

My request would be to assign the back button (one press) to delete text while typing.

Could that be implemented?

![whatsapp image 2018-08-06 at 11 05 35](https://user-images.githubusercontent.com/42135570/43704619-ebeef142-9968-11e8-8f5c-a1f1a6699952.jpeg)

**Comment by Clam-** [comment]
Hi,

That is unfortunate that there is no Del key. However I would strongly advise against using the back key, as the back key controls important navigation functions in the Android system and IME subsystem.
Perhaps you could [KeyMap](https://github.com/Clam-/TraditionalT9/wiki/Key-remapping) the Down key to Del.

**Comment by Kallemies** [comment]
Hi, in multiple Android phys. keyboard phones I have owned, the back key has usually been used as the key to delete the text.

It is implemented so that when you are typing and press the key once, it removes one character.

If you double press the back key, then it does the normal things the back key does.

What do you think of this?

**Comment by Kallemies** [comment]
I mean, is it possible to edit the back key to:

when you press it once, it deletes text

when you double press it, it functions normally.

**Comment by HenriDellal** [comment]
Hello.
I've found that the preinstalled keyboard on my phone is a fork of this one. Since the phone doesn't have the Delete button, the keyboard has an on-screen key for deletion. I'm trying to add it in the application, but call to handleBackspace() (it's public in my fork) doesn't work as expected. I miss something probably.

**Comment by Clam-** [comment]
I'm not sure what you are trying to achieve. Can you elaborate?
Are you trying to make a modification to add an on screen button? Or are you trying to call handleBackspace from some where?
If you have a fork can you link to the line of code you are having problems with?

**Comment by HenriDellal** [comment]
I was trying to add an on-screen button and call handleBackspace when it is pressed. I've found the mistake and it works now. I've uploaded fork now at https://github.com/HenriDellal/TraditionalT9

It has more changes (layout fixes, etc). If you want, I can make a PR to discuss them, because it requires some work still.

**Comment by udif** [comment]
@HenriDellal what happened to your fork?

**Comment by HenriDellal** [comment]
@udif I moved repos to codeberg, you can find the fork [here](https://codeberg.org/HenriDellal/TraditionalT9)

**Comment by Saphar** [comment]
I have the same issue, is it possible to use for this the keymap.txt file? How do we use that file, when I try to load it it doesn't find it. Where should I place it? (I did not run the code directly but installed an apk)

**Comment by Clam-** [comment]
> How do we use that file, when I try to load it it doesn't find it. Where should I place it?
https://github.com/Clam-/TraditionalT9/wiki/Key-remapping
